In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
# from sklearn.compose import Columnransformer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [17]:
df=pd.read_csv("train2.csv",usecols=["Age","Pclass","Fare","Survived"])
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [18]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [19]:
X=df.drop(columns='Survived')
Y=df['Survived']

In [20]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=2,test_size=0.2)

In [ ]:
X_train.head()

     Pclass   Age     Fare
30        1  40.0  27.7208
10        3   4.0  16.7000
873       3  47.0   9.0000
182       3   9.0  31.3875
876       3  20.0   9.8458

In [ ]:
KNN=KNNImputer(n_neighbors=3,weights='distance')
X_train_trf=KNN.fit_transform(X_train)
X_test_trf=KNN.transform(X_test)

In [30]:
lr=LogisticRegression()
lr.fit(X_train_trf,Y_train)

y_pred=lr.predict(X_test_trf)

accuracy_score(Y_test,y_pred)

0.7094972067039106

In [32]:
#comaprison with simple imputer

si=SimpleImputer()

X_train_trf2=si.fit_transform(X_train)
X_test_trf2=si.transform(X_test)

lr.fit(X_train_trf2,Y_train)
y_pred2=lr.predict(X_test_trf2)

accuracy_score(Y_test,y_pred2)

0.6927374301675978